Update requirements of `clickhouse-connect`
Using version 0.5 or above breaks the `http` connection for clickhouse. Adding anything in `custom_settings` in profiles.yml leads to the following error when you run `dbt debug`

```
1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:
                                              
  >Database Error
  __init__() got an unexpected keyword argument 'max_insert_threads'
```